### ISSUE TITLE
Not able to download on your downloader 

### ISSUE THREAD

**Issue by malzen** [Tenpi/Crunchyroll-Downloader#37] opened 2021-10-17 19:57 UTC
Please could you make a fix for this.

**Comment by Tenpi** [comment] 2021-10-17 20:32
Not able to download what?

**Comment by malzen** [comment] 2021-10-17 21:01
Anything on the Beta Crunchyroll website

**Comment by KeronCyst** [comment] 2021-11-23 14:13
USA here on non-beta CR. This yields NaNs and then a premium warning when paused, even though it's not premium:

https://www.crunchyroll.com/my-hero-academia/episode-64-the-scoop-on-ua-class-1-a-789679

**Comment by Tenpi** [comment] 2022-02-10 23:46
Closing can't reproduce

**Closed by Tenpi** 2022-02-10 23:46 UTC
Labels: invalid
