### ISSUE TITLE
Certain animes/episodes do not download

### ISSUE THREAD

**Issue by minecraftkiller006** [Tenpi/Crunchyroll-Downloader#40] opened 2021-11-18 00:15 UTC
For animes that don't change in name (e.g. attack on titan or quintessential quintuplets) the episodes of season 2 and onwards cannot all be downloaded (in AOT's case, none can be downloaded, in quintessential's case, only some can be downloaded; please try to accommodate for these sort of links.

**Comment by lucaslira95** [comment] 2022-02-06 22:19
Blade Runner: Black Lotus not working here, other animes are ok.

**Comment by Tenpi** [comment] 2022-02-16 02:33
Cannot reproduce, closing, I have downloaded all the mentioned animes just fine

**Closed by Tenpi** 2022-02-16 02:33 UTC
Labels: invalid
