### ISSUE TITLE
Damaged Videos

### ISSUE THREAD

**Issue by SAOKT** [Tenpi/Crunchyroll-Downloader#31] opened 2021-08-14 03:12 UTC
For some reason, no video that I download with this program is downloaded without errors.
If the program download, it finishes the download without problem.

but when i play the video somewhere it always freezes.

I suppose it is damaged oh it does not download any fragment of the video.

it happens to me with all the videos.

Some reason why this happens to me I already tried the program on 2 different computers.

and if I have a premium account.

**Comment by Tenpi** [comment] 2021-08-14 09:10
Have you tried using another video player? Which videos are you downloading..?

**Comment by SAOKT** [comment] 2021-08-14 12:19
I already tried other players.

I have downloaded it in Spanish, Latin and Japanese, but they are still downloaded incomplete.

example a video that weighs 1.33 GB.
in my case it weighs 1.28 gb.

in the second pc download the same chapter and it weighs 1.30.

I don't know why it happens to me, but the videos are downloaded incomplete. and that causes some frame to be damaged.

my pc 1: has an i7-4790k. 16 GB RAM.

my second pc has a lga 775. a quad core. 8GB RAM.

**Comment by SAOKT** [comment] 2021-08-14 12:21
I have windows 1st pro 64 bts.

the second pc windows 8.1 pro 64 bits.

**Comment by Tenpi** [comment] 2021-08-14 16:08
Can you run the following command on one of the damaged videos and paste the output here please?
`ffmpeg -v error -i "path/to/input.mp4" -f null - 2> "path/to/error.log"`

If you don't already have ffmpeg installed, download it from https://www.ffmpeg.org/ and add it to your PATH environmental variable. Also, if the resulting file is empty it means that the video has no errors and the problem is something else.

**Comment by SAOKT** [comment] 2021-08-14 23:27
ffmpeg -v error -i "C:\FFmpeg\1.mp4" -f null - 2> "C:\FFmpeg\error.log"

I tried but it just generates a blank file for me.

my internet is 20 megabytes.

**Comment by Tenpi** [comment] 2021-08-15 00:38
> ffmpeg -v error -i "C:\FFmpeg\1.mp4" -f null - 2> "C:\FFmpeg\error.log"
> 
> I tried but it just generates a blank file for me.

It doesn't seem like the videos are damaged, then. If you can upload an example somewhere I'll see if I'm able to play them without freezing. Otherwise, this seems more like a problem which is exclusive to your computer, maybe its the video players you are using or they are simply not powerful enough to play the videos without freezing. The LGA 775 is a pretty old CPU dating back to 2004. I don't see why you'd have problems with the i7 computer, though.

**Comment by Tenpi** [comment] 2021-08-16 20:44
Closing as this is probably a problem on your end.

**Closed by Tenpi** 2021-08-16 20:44 UTC
Labels: invalid
